### ISSUE TITLE
bug/CB needs at least 1 house to be applied

### ISSUE THREAD

**Issue by Luktronic** [Ardas-Legends-Development-Team/AL-frontend#18]
At the moment when creating a Claimbuild Application in the UI, the user has to add at least 1 house to the CB.
However, some CBs (like Castles) do not need houses in order to be accepted.

![image](https://github.com/Ardas-Legends-Development-Team/AL-frontend/assets/59698507/7bf2fc51-30e2-4d96-a816-8fa69f05b92b)

## Fix
Check which CB Type is selected and do the house check based on that

**Comment by VernonRoche** [comment]
@Luktronic has this been fixed yet?

**Comment by Luktronic** [comment]
> @Luktronic has this been fixed yet?

Don't think so
