### ISSUE TITLE
qol/factions in alphabetical order

### ISSUE THREAD

**Issue by Luktronic** [Ardas-Legends-Development-Team/AL-frontend#22]
We could display the factions on the faction page in alphabetical order.
Not really a need to do that but it was suggested

![image](https://github.com/Ardas-Legends-Development-Team/AL-frontend/assets/59698507/7764cae5-75ef-4b8d-80ad-02ff8e8b0100)

**Comment by SimonManwe** [comment]
https://github.com/Ardas-Legends-Development-Team/AL-frontend/pull/78
