### ISSUE TITLE
Bug/Image preloading not working

### ISSUE THREAD

**Issue by VernonRoche** [Ardas-Legends-Development-Team/AL-frontend#71]
**Describe the bug or feature**
Normally in order to load images faster, we fetch a low-resolution variant of it (loads quicker) and then it progressively loads the normal image, however the loading of the small image takes time and there is a time where no image exists and it's visible in the interface (nothing exists instead)

**Describe the solution and what is need to be done**
Now we fetch the small image from the CDN but since there's a latency there, the LazyLoadedImage component should be changed. Instead the low resolution image should be loaded locally from the server, and only the real image be loaded by the CDN.

Maybe there is another solution, like fixing the container div to the image's size (which would be better), or maybe add a skeleton.

**Comment by SimonManwe** [comment]
https://github.com/Ardas-Legends-Development-Team/AL-frontend/pull/81
