### ISSUE TITLE
Bug/Claimbuild detail and rpchar modal in faction dashboard bug

### ISSUE THREAD

**Issue by VernonRoche** [Ardas-Legends-Development-Team/AL-frontend#83]
**Describe the bug or feature**
When we click on the CB detail modal or the rpchar detail modal in the faction dashboard we get an error.

**Describe the solution and what is need to be done**
Seems I may have messed up the different ways to make a modal, and probably tried to use the new HTML method of doing it, but ended up messing with it. They should use the same format as all modals.

**Additional context**
![image](https://github.com/user-attachments/assets/476b1c2e-a4a1-499f-8e04-15d4cc9ee031)

**Comment by SimonManwe** [comment]
will be fixed in https://github.com/Ardas-Legends-Development-Team/AL-frontend/pull/91 also an explanation for what caused this can be found there :)
